# PGA Tour player stats for one season

In [ ]:
%pip install requests pandas python-dotenv pymysql sqlalchemy

In [2]:
import os
import json #handle API response
import requests #send requests to API
import pandas as pd #data transformation
from mysql import connector #connect to mySQL
from sqlalchemy import create_engine
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

In [4]:
API_KEY = os.getenv("API_KEY")
API_HOST = os.getenv("API_HOST")
ACCESS_LEVEL = "trial"
GOLF_TOUR = "pga"
LANGUAGE_CODE = "en"
SEASON_YEAR = 2026
FORMAT = "json"

In [5]:
url = f"https://api.sportradar.com/golf/{ACCESS_LEVEL}/{GOLF_TOUR}/v3/{LANGUAGE_CODE}/{SEASON_YEAR}/players/statistics.{FORMAT}"
headers = {
    "x-api-key": API_KEY,
    "x-api-host": API_HOST
}
querystring = {
    "season": SEASON_YEAR,
    "tour": GOLF_TOUR
}

# ------- EXTRACT --------

In [6]:
response = requests.get(url=url,
                        headers=headers,
                        params=querystring)

In [7]:
payload = response.json()

In [8]:
formatted_response = json.dumps(payload, indent=4)
print(formatted_response)

{
    "tour": {
        "id": "b52068af-28e4-4e91-bdbb-037591b0ff84",
        "alias": "pga",
        "name": "PGA Tour",
        "currency": "USD"
    },
    "season": {
        "id": "e4694c64-017f-432f-b80e-28bcec314ca6",
        "year": 2026
    },
    "players": [
        {
            "id": "da226913-b804-48de-adbf-96e956eb75ac",
            "first_name": "Rory",
            "last_name": "McIlroy",
            "country": "NORTHERN IRELAND",
            "abbr_name": "R.McIlroy",
            "statistics": {
                "events_played": 14,
                "first_place": 1,
                "second_place": 1,
                "third_place": 1,
                "top_10": 6,
                "top_25": 9,
                "cuts": 0,
                "cuts_made": 14,
                "withdrawals": 1,
                "points": 2095.0,
                "points_rank": 4,
                "earnings": 11573749.0,
                "earnings_rank": 5,
                "drive_avg": 330.3,
                "drive_acc": 54.65,
                "gir_pct": 68.62,
                "putt_avg": 1.739,
                "sand_saves_pct": 56.04,
                "birdies_per_round": 4.31,
                "holes_per_eagle": 138.9,
                "world_rank": 2,
                "strokes_gained": 0.243,
                "hole_proximity_avg": "36' 11\"",
                "scrambling_pct": 59.34,
                "scoring_avg": 69.342,
                "strokes_gained_tee_green": 1.098,
                "strokes_gained_total": 1.341,
                "total_driving": 137,
                "all_around_ranking": 7
            }
        },
        {
            "id": "da8b4888-9330-46d0-8f8a-f76fae949dba",
            "first_name": "Jackson",
            "last_name": "Suber",
            "country": "UNITED STATES",
            "abbr_name": "J.Suber",
            "statistics": {
                "events_played": 20,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 3,
                "top_25": 6,
                "cuts": 7,
                "cuts_made": 13,
                "withdrawals": 0,
                "points": 554.0,
                "points_rank": 74,
                "earnings": 1782277.0,
                "earnings_rank": 78,
                "drive_avg": 306.2,
                "drive_acc": 60.78,
                "gir_pct": 70.68,
                "putt_avg": 1.776,
                "sand_saves_pct": 54.55,
                "birdies_per_round": 4.18,
                "holes_per_eagle": 146.3,
                "world_rank": 94,
                "strokes_gained": -0.291,
                "hole_proximity_avg": "33' 6\"",
                "scrambling_pct": 61.52,
                "scoring_avg": 70.31,
                "strokes_gained_tee_green": 0.767,
                "strokes_gained_total": 0.475,
                "total_driving": 158,
                "all_around_ranking": 24
            }
        },
        {
            "id": "7a4b2b40-4675-41d9-86fd-cc6a61a1d3b2",
            "first_name": "Nicolai",
            "last_name": "H\u00f8jgaard",
            "country": "DENMARK",
            "abbr_name": "N.H\u00f8jgaard",
            "statistics": {
                "events_played": 21,
                "first_place": 0,
                "second_place": 2,
                "third_place": 1,
                "top_10": 4,
                "top_25": 8,
                "cuts": 5,
                "cuts_made": 16,
                "withdrawals": 0,
                "points": 1228.0,
                "points_rank": 35,
                "earnings": 4914868.0,
                "earnings_rank": 35,
                "drive_avg": 325.1,
                "drive_acc": 52.64,
                "gir_pct": 65.39,
                "putt_avg": 1.749,
                "sand_saves_pct": 50.0,
                "birdies_per_round": 3.68,
                "holes_per_eagle": 88.8,
                "world_rank": 42,
                "strokes_gained": 0.099,
                "hole_proximity_avg": "37' 6\"",
                "scrambling_pct": 60.52,
                "scoring_avg": 70.168,
                "strokes_gained_tee_green": 0.592,
                "strokes_gained_total": 0.691,
                "total_driving": 155,
                "all_around_ranking": 68
            }
        },
        {
            "id": "a9053c60-3cc0-48cb-bcf2-4848963f352d",
            "first_name": "Kris",
            "last_name": "Ventura",
            "country": "NORWAY",
            "abbr_name": "K.Ventura",
            "statistics": {
                "events_played": 19,
                "first_place": 0,
                "second_place": 1,
                "third_place": 0,
                "top_10": 3,
                "top_25": 5,
                "cuts": 12,
                "cuts_made": 7,
                "withdrawals": 0,
                "points": 373.0,
                "points_rank": 107,
                "earnings": 1180422.0,
                "earnings_rank": 105,
                "drive_avg": 312.8,
                "drive_acc": 63.24,
                "gir_pct": 69.73,
                "putt_avg": 1.774,
                "sand_saves_pct": 53.85,
                "birdies_per_round": 3.53,
                "holes_per_eagle": 63.0,
                "world_rank": 195,
                "strokes_gained": -0.03,
                "hole_proximity_avg": "34' 3\"",
                "scrambling_pct": 62.17,
                "scoring_avg": 70.693,
                "strokes_gained_tee_green": 0.225,
                "strokes_gained_total": 0.195,
                "total_driving": 77,
                "all_around_ranking": 35
            }
        },
        {
            "id": "9b625995-cfb6-4ae6-91bb-b736b7d56bf7",
            "first_name": "Gordon",
            "last_name": "Sargent",
            "country": "UNITED STATES",
            "abbr_name": "G.Sargent",
            "statistics": {
                "events_played": 18,
                "first_place": 0,
                "second_place": 1,
                "third_place": 0,
                "top_10": 2,
                "top_25": 3,
                "cuts": 11,
                "cuts_made": 7,
                "withdrawals": 0,
                "points": 232.0,
                "points_rank": 132,
                "earnings": 599780.0,
                "earnings_rank": 136,
                "drive_avg": 320.1,
                "drive_acc": 60.15,
                "gir_pct": 66.31,
                "putt_avg": 1.759,
                "sand_saves_pct": 51.61,
                "birdies_per_round": 4.04,
                "holes_per_eagle": 169.2,
                "world_rank": 331,
                "strokes_gained": -0.209,
                "hole_proximity_avg": "42' 3\"",
                "scrambling_pct": 55.79,
                "scoring_avg": 71.602,
                "strokes_gained_tee_green": -0.486,
                "strokes_gained_total": -0.694,
                "total_driving": 98,
                "all_around_ranking": 80
            }
        },
        {
            "id": "606d1a25-2e9a-4e9f-95a2-c0947bb52912",
            "first_name": "Rasmus",
            "last_name": "Neergaard-Petersen",
            "country": "DENMARK",
            "abbr_name": "R.Neergaard-Petersen",
            "statistics": {
                "events_played": 18,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 2,
                "top_25": 4,
                "cuts": 5,
                "cuts_made": 13,
                "withdrawals": 0,
                "points": 404.0,
                "points_rank": 102,
                "earnings": 1098718.0,
                "earnings_rank": 111,
                "drive_avg": 308.4,
                "drive_acc": 62.09,
                "gir_pct": 67.24,
                "putt_avg": 1.792,
                "sand_saves_pct": 31.76,
                "birdies_per_round": 3.5,
                "holes_per_eagle": 104.4,
                "world_rank": 72,
                "strokes_gained": 0.032,
                "hole_proximity_avg": "38' 7\"",
                "scrambling_pct": 57.02,
                "scoring_avg": 70.54,
                "strokes_gained_tee_green": 0.212,
                "strokes_gained_total": 0.244,
                "total_driving": 111,
                "all_around_ranking": 105
            }
        },
        {
            "id": "cb867fe8-660d-43de-9486-c80cc0837190",
            "first_name": "Henrik",
            "last_name": "Norlander",
            "country": "SWEDEN",
            "abbr_name": "H.Norlander",
            "statistics": {
                "events_played": 7,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 0,
                "cuts": 5,
                "cuts_made": 2,
                "withdrawals": 0,
                "points": 6.0,
                "points_rank": 206,
                "earnings": 28015.0,
                "earnings_rank": 206,
                "drive_avg": 281.4,
                "drive_acc": 61.01,
                "gir_pct": 59.72,
                "putt_avg": 1.75,
                "sand_saves_pct": 50.0,
                "birdies_per_round": 3.25,
                "holes_per_eagle": 144.0,
                "world_rank": 561,
                "strokes_gained": -0.484,
                "hole_proximity_avg": "37' 7\"",
                "scrambling_pct": 52.59,
                "scoring_avg": 72.854,
                "strokes_gained_tee_green": -1.357,
                "strokes_gained_total": -1.842
            }
        },
        {
            "id": "17d9be3d-a0a4-4a8c-a2ac-d127050f42c0",
            "first_name": "Fabi\u00e1n",
            "last_name": "G\u00f3mez",
            "country": "ARGENTINA",
            "abbr_name": "F.G\u00f3mez",
            "statistics": {
                "events_played": 7,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 0,
                "cuts": 2,
                "cuts_made": 5,
                "withdrawals": 0,
                "points": 25.0,
                "points_rank": 199,
                "earnings": 85851.0,
                "earnings_rank": 198,
                "drive_avg": 292.4,
                "drive_acc": 75.15,
                "gir_pct": 67.36,
                "putt_avg": 1.749,
                "sand_saves_pct": 53.66,
                "birdies_per_round": 4.08,
                "holes_per_eagle": 432.0,
                "world_rank": 445,
                "strokes_gained": -0.57,
                "hole_proximity_avg": "37' 3\"",
                "scrambling_pct": 62.41,
                "scoring_avg": 71.825,
                "strokes_gained_tee_green": -0.128,
                "strokes_gained_total": -0.698
            }
        },
        {
            "id": "0b5d3fd6-e3ec-4efd-8743-60db44c87425",
            "first_name": "Keegan",
            "last_name": "Bradley",
            "country": "UNITED STATES",
            "abbr_name": "K.Bradley",
            "statistics": {
                "events_played": 20,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 6,
                "cuts": 4,
                "cuts_made": 16,
                "withdrawals": 0,
                "points": 548.0,
                "points_rank": 77,
                "earnings": 2225547.0,
                "earnings_rank": 66,
                "drive_avg": 311.6,
                "drive_acc": 60.96,
                "gir_pct": 66.59,
                "putt_avg": 1.764,
                "sand_saves_pct": 52.46,
                "birdies_per_round": 3.82,
                "holes_per_eagle": 99.7,
                "world_rank": 50,
                "strokes_gained": -0.089,
                "hole_proximity_avg": "36' 1\"",
                "scrambling_pct": 57.27,
                "scoring_avg": 70.556,
                "strokes_gained_tee_green": 0.548,
                "strokes_gained_total": 0.459,
                "total_driving": 114,
                "all_around_ranking": 44
            }
        },
        {
            "id": "229faa9c-fc01-46bb-a8cb-f6b0310a8cef",
            "first_name": "Sam",
            "last_name": "Ryder",
            "country": "UNITED STATES",
            "abbr_name": "S.Ryder",
            "statistics": {
                "events_played": 12,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 2,
                "cuts": 4,
                "cuts_made": 8,
                "withdrawals": 0,
                "points": 138.0,
                "points_rank": 153,
                "earnings": 368375.0,
                "earnings_rank": 155,
                "drive_avg": 299.4,
                "drive_acc": 57.25,
                "gir_pct": 67.84,
                "putt_avg": 1.716,
                "sand_saves_pct": 51.72,
                "birdies_per_round": 3.97,
                "holes_per_eagle": 136.8,
                "world_rank": 283,
                "strokes_gained": 0.445,
                "hole_proximity_avg": "34' 9\"",
                "scrambling_pct": 59.09,
                "scoring_avg": 70.82,
                "strokes_gained_tee_green": 0.116,
                "strokes_gained_total": 0.561,
                "total_driving": 237,
                "all_around_ranking": 48
            }
        },
        {
            "id": "7319e8bc-da2f-40a4-8e28-51ad3b28eb2a",
            "first_name": "Alejandro",
            "last_name": "Tosti",
            "country": "ARGENTINA",
            "abbr_name": "A.Tosti",
            "statistics": {
                "events_played": 22,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 0,
                "cuts": 18,
                "cuts_made": 4,
                "withdrawals": 0,
                "points": 54.0,
                "points_rank": 188,
                "earnings": 125412.0,
                "earnings_rank": 192,
                "drive_avg": 313.2,
                "drive_acc": 56.23,
                "gir_pct": 61.87,
                "putt_avg": 1.794,
                "sand_saves_pct": 46.05,
                "birdies_per_round": 3.57,
                "holes_per_eagle": 306.0,
                "world_rank": 493,
                "strokes_gained": -0.862,
                "hole_proximity_avg": "39' 1\"",
                "scrambling_pct": 54.29,
                "scoring_avg": 72.53,
                "strokes_gained_tee_green": -0.735,
                "strokes_gained_total": -1.597,
                "total_driving": 160,
                "all_around_ranking": 152
            }
        },
        {
            "id": "72b7246a-6391-4024-8d0f-35fa1c459664",
            "first_name": "Cameron",
            "last_name": "Champ",
            "country": "UNITED STATES",
            "abbr_name": "C.Champ",
            "statistics": {
                "events_played": 8,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 0,
                "top_25": 0,
                "cuts": 4,
                "cuts_made": 3,
                "withdrawals": 1,
                "points": 13.0,
                "points_rank": 201,
                "earnings": 33016.0,
                "earnings_rank": 204,
                "drive_avg": 318.5,
                "drive_acc": 66.79,
                "gir_pct": 69.88,
                "putt_avg": 1.803,
                "sand_saves_pct": 55.88,
                "birdies_per_round": 3.37,
                "holes_per_eagle": 171.0,
                "world_rank": 441,
                "strokes_gained": -0.297,
                "hole_proximity_avg": "37' 5\"",
                "scrambling_pct": 56.31,
                "scoring_avg": 72.133,
                "strokes_gained_tee_green": -0.767,
                "strokes_gained_total": -1.063
            }
        },
        {
            "id": "8169868c-7b2c-45ff-a9fa-4628f463845a",
            "first_name": "Jackson",
            "last_name": "Koivun",
            "country": "UNITED STATES",
            "abbr_name": "J.Koivun",
            "statistics": {
                "events_played": 8,
                "first_place": 1,
                "second_place": 0,
                "third_place": 0,
                "top_10": 3,
                "top_25": 5,
                "cuts": 1,
                "cuts_made": 7,
                "withdrawals": 0,
                "points": 730.0,
                "points_rank": 62,
                "earnings": 2140387.0,
                "earnings_rank": 67,
                "drive_avg": 307.5,
                "drive_acc": 73.32,
                "gir_pct": 73.7,
                "putt_avg": 1.749,
                "sand_saves_pct": 50.0,
                "birdies_per_round": 4.2,
                "holes_per_eagle": 135.0,
                "world_rank": 58,
                "strokes_gained": 0.153,
                "hole_proximity_avg": "33' 4\"",
                "scrambling_pct": 63.38,
                "scoring_avg": 68.751,
                "strokes_gained_tee_green": 1.43,
                "strokes_gained_total": 1.583
            }
        },
        {
            "id": "77a9104b-6fd4-40b7-85e2-10b2448a8f86",
            "first_name": "Kevin",
            "last_name": "Yu",
            "country": "CHINESE TAIPEI",
            "abbr_name": "K.Yu",
            "statistics": {
                "events_played": 21,
                "first_place": 0,
                "second_place": 0,
                "third_place": 0,
                "top_10": 2,
                "top_25": 6,
                "cuts": 9,
                "cuts_made": 12,
                "withdrawals": 0,
                "points": 472.0,
                "points_rank": 93,
                "earnings": 1357836.0,
                "earnings_rank": 97,
                "drive_avg": 309.7,
                "drive_acc": 61.25,
                "gir_pct": 69.49,
                "putt_avg": 1.726,
                "sand_saves_pct": 54.55,
                "birdies_per_round": 4.38,
                "holes_per_eagle": 106.4,
                "world_rank": 105,
                "strokes_gained": -0.123,
                "hole_proximity_avg": "36' 10\"",
                "scrambling_pct": 58.26,
                "scoring_avg": 70.588,
                "strokes_gained_tee_green": 0.546,
                "strokes_gained_total": 0.424,
                "total_driving": 120,
                "all_around_ranking": 4
            }
        },
        {
            "id": "3888a78e-b24a-4005-8915-2f03fccf3107",
            "first_name": "Patrick",
            "last_name": "Rodgers",
            "country": "UNITED STATES",
            "abbr_name": "P.Rodgers",
            "statistics": {
                "events_played": 23,
                "first_place": 0,
                "second_place": 0,
                "third_place": 1,
                "top_10": 1,
                "top_25": 6,
                "cuts": 5,
                "cuts_made": 17,
                "withdrawals": 1,
                "points": 657.0,
                "points_rank": 67,
                "earnings": 2538290.0,
                "earnings_rank": 62,
                "drive_avg": 308.4,
                "drive_acc": 54.45,
                "gir_pct": 63.08,
                "putt_avg": 1.742,
                "sand_saves_pct": 48.28,
                "birdies_per_round": 3.75,
                "holes_per_eagle": 129.3,
                "world_rank": 107,
                "strokes_gained": 0.228,
                "hole_proximity_avg": "38' 7\"",

# --------- TRANSFORM ------------

In [9]:
players_list = payload["players"]
players_list

[{'id': 'da226913-b804-48de-adbf-96e956eb75ac',
  'first_name': 'Rory',
  'last_name': 'McIlroy',
  'country': 'NORTHERN IRELAND',
  'abbr_name': 'R.McIlroy',
  'statistics': {'events_played': 14,
   'first_place': 1,
   'second_place': 1,
   'third_place': 1,
   'top_10': 6,
   'top_25': 9,
   'cuts': 0,
   'cuts_made': 14,
   'withdrawals': 1,
   'points': 2095.0,
   'points_rank': 4,
   'earnings': 11573749.0,
   'earnings_rank': 5,
   'drive_avg': 330.3,
   'drive_acc': 54.65,
   'gir_pct': 68.62,
   'putt_avg': 1.739,
   'sand_saves_pct': 56.04,
   'birdies_per_round': 4.31,
   'holes_per_eagle': 138.9,
   'world_rank': 2,
   'strokes_gained': 0.243,
   'hole_proximity_avg': '36\' 11"',
   'scrambling_pct': 59.34,
   'scoring_avg': 69.342,
   'strokes_gained_tee_green': 1.098,
   'strokes_gained_total': 1.341,
   'total_driving': 137,
   'all_around_ranking': 7}},
 {'id': 'da8b4888-9330-46d0-8f8a-f76fae949dba',
  'first_name': 'Jackson',
  'last_name': 'Suber',
  'country': 'UNITED STATES',
  'abbr_name': 'J.Suber',
  'statistics': {'events_played': 20,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 3,
   'top_25': 6,
   'cuts': 7,
   'cuts_made': 13,
   'withdrawals': 0,
   'points': 554.0,
   'points_rank': 74,
   'earnings': 1782277.0,
   'earnings_rank': 78,
   'drive_avg': 306.2,
   'drive_acc': 60.78,
   'gir_pct': 70.68,
   'putt_avg': 1.776,
   'sand_saves_pct': 54.55,
   'birdies_per_round': 4.18,
   'holes_per_eagle': 146.3,
   'world_rank': 94,
   'strokes_gained': -0.291,
   'hole_proximity_avg': '33\' 6"',
   'scrambling_pct': 61.52,
   'scoring_avg': 70.31,
   'strokes_gained_tee_green': 0.767,
   'strokes_gained_total': 0.475,
   'total_driving': 158,
   'all_around_ranking': 24}},
 {'id': '7a4b2b40-4675-41d9-86fd-cc6a61a1d3b2',
  'first_name': 'Nicolai',
  'last_name': 'Højgaard',
  'country': 'DENMARK',
  'abbr_name': 'N.Højgaard',
  'statistics': {'events_played': 21,
   'first_place': 0,
   'second_place': 2,
   'third_place': 1,
   'top_10': 4,
   'top_25': 8,
   'cuts': 5,
   'cuts_made': 16,
   'withdrawals': 0,
   'points': 1228.0,
   'points_rank': 35,
   'earnings': 4914868.0,
   'earnings_rank': 35,
   'drive_avg': 325.1,
   'drive_acc': 52.64,
   'gir_pct': 65.39,
   'putt_avg': 1.749,
   'sand_saves_pct': 50.0,
   'birdies_per_round': 3.68,
   'holes_per_eagle': 88.8,
   'world_rank': 42,
   'strokes_gained': 0.099,
   'hole_proximity_avg': '37\' 6"',
   'scrambling_pct': 60.52,
   'scoring_avg': 70.168,
   'strokes_gained_tee_green': 0.592,
   'strokes_gained_total': 0.691,
   'total_driving': 155,
   'all_around_ranking': 68}},
 {'id': 'a9053c60-3cc0-48cb-bcf2-4848963f352d',
  'first_name': 'Kris',
  'last_name': 'Ventura',
  'country': 'NORWAY',
  'abbr_name': 'K.Ventura',
  'statistics': {'events_played': 19,
   'first_place': 0,
   'second_place': 1,
   'third_place': 0,
   'top_10': 3,
   'top_25': 5,
   'cuts': 12,
   'cuts_made': 7,
   'withdrawals': 0,
   'points': 373.0,
   'points_rank': 107,
   'earnings': 1180422.0,
   'earnings_rank': 105,
   'drive_avg': 312.8,
   'drive_acc': 63.24,
   'gir_pct': 69.73,
   'putt_avg': 1.774,
   'sand_saves_pct': 53.85,
   'birdies_per_round': 3.53,
   'holes_per_eagle': 63.0,
   'world_rank': 195,
   'strokes_gained': -0.03,
   'hole_proximity_avg': '34\' 3"',
   'scrambling_pct': 62.17,
   'scoring_avg': 70.693,
   'strokes_gained_tee_green': 0.225,
   'strokes_gained_total': 0.195,
   'total_driving': 77,
   'all_around_ranking': 35}},
 {'id': '9b625995-cfb6-4ae6-91bb-b736b7d56bf7',
  'first_name': 'Gordon',
  'last_name': 'Sargent',
  'country': 'UNITED STATES',
  'abbr_name': 'G.Sargent',
  'statistics': {'events_played': 18,
   'first_place': 0,
   'second_place': 1,
   'third_place': 0,
   'top_10': 2,
   'top_25': 3,
   'cuts': 11,
   'cuts_made': 7,
   'withdrawals': 0,
   'points': 232.0,
   'points_rank': 132,
   'earnings': 599780.0,
   'earnings_rank': 136,
   'drive_avg': 320.1,
   'drive_acc': 60.15,
   'gir_pct': 66.31,
   'putt_avg': 1.759,
   'sand_saves_pct': 51.61,
   'birdies_per_round': 4.04,
   'holes_per_eagle': 169.2,
   'world_rank': 331,
   'strokes_gained': -0.209,
   'hole_proximity_avg': '42\' 3"',
   'scrambling_pct': 55.79,
   'scoring_avg': 71.602,
   'strokes_gained_tee_green': -0.486,
   'strokes_gained_total': -0.694,
   'total_driving': 98,
   'all_around_ranking': 80}},
 {'id': '606d1a25-2e9a-4e9f-95a2-c0947bb52912',
  'first_name': 'Rasmus',
  'last_name': 'Neergaard-Petersen',
  'country': 'DENMARK',
  'abbr_name': 'R.Neergaard-Petersen',
  'statistics': {'events_played': 18,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 2,
   'top_25': 4,
   'cuts': 5,
   'cuts_made': 13,
   'withdrawals': 0,
   'points': 404.0,
   'points_rank': 102,
   'earnings': 1098718.0,
   'earnings_rank': 111,
   'drive_avg': 308.4,
   'drive_acc': 62.09,
   'gir_pct': 67.24,
   'putt_avg': 1.792,
   'sand_saves_pct': 31.76,
   'birdies_per_round': 3.5,
   'holes_per_eagle': 104.4,
   'world_rank': 72,
   'strokes_gained': 0.032,
   'hole_proximity_avg': '38\' 7"',
   'scrambling_pct': 57.02,
   'scoring_avg': 70.54,
   'strokes_gained_tee_green': 0.212,
   'strokes_gained_total': 0.244,
   'total_driving': 111,
   'all_around_ranking': 105}},
 {'id': 'cb867fe8-660d-43de-9486-c80cc0837190',
  'first_name': 'Henrik',
  'last_name': 'Norlander',
  'country': 'SWEDEN',
  'abbr_name': 'H.Norlander',
  'statistics': {'events_played': 7,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 0,
   'cuts': 5,
   'cuts_made': 2,
   'withdrawals': 0,
   'points': 6.0,
   'points_rank': 206,
   'earnings': 28015.0,
   'earnings_rank': 206,
   'drive_avg': 281.4,
   'drive_acc': 61.01,
   'gir_pct': 59.72,
   'putt_avg': 1.75,
   'sand_saves_pct': 50.0,
   'birdies_per_round': 3.25,
   'holes_per_eagle': 144.0,
   'world_rank': 561,
   'strokes_gained': -0.484,
   'hole_proximity_avg': '37\' 7"',
   'scrambling_pct': 52.59,
   'scoring_avg': 72.854,
   'strokes_gained_tee_green': -1.357,
   'strokes_gained_total': -1.842}},
 {'id': '17d9be3d-a0a4-4a8c-a2ac-d127050f42c0',
  'first_name': 'Fabián',
  'last_name': 'Gómez',
  'country': 'ARGENTINA',
  'abbr_name': 'F.Gómez',
  'statistics': {'events_played': 7,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 0,
   'cuts': 2,
   'cuts_made': 5,
   'withdrawals': 0,
   'points': 25.0,
   'points_rank': 199,
   'earnings': 85851.0,
   'earnings_rank': 198,
   'drive_avg': 292.4,
   'drive_acc': 75.15,
   'gir_pct': 67.36,
   'putt_avg': 1.749,
   'sand_saves_pct': 53.66,
   'birdies_per_round': 4.08,
   'holes_per_eagle': 432.0,
   'world_rank': 445,
   'strokes_gained': -0.57,
   'hole_proximity_avg': '37\' 3"',
   'scrambling_pct': 62.41,
   'scoring_avg': 71.825,
   'strokes_gained_tee_green': -0.128,
   'strokes_gained_total': -0.698}},
 {'id': '0b5d3fd6-e3ec-4efd-8743-60db44c87425',
  'first_name': 'Keegan',
  'last_name': 'Bradley',
  'country': 'UNITED STATES',
  'abbr_name': 'K.Bradley',
  'statistics': {'events_played': 20,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 6,
   'cuts': 4,
   'cuts_made': 16,
   'withdrawals': 0,
   'points': 548.0,
   'points_rank': 77,
   'earnings': 2225547.0,
   'earnings_rank': 66,
   'drive_avg': 311.6,
   'drive_acc': 60.96,
   'gir_pct': 66.59,
   'putt_avg': 1.764,
   'sand_saves_pct': 52.46,
   'birdies_per_round': 3.82,
   'holes_per_eagle': 99.7,
   'world_rank': 50,
   'strokes_gained': -0.089,
   'hole_proximity_avg': '36\' 1"',
   'scrambling_pct': 57.27,
   'scoring_avg': 70.556,
   'strokes_gained_tee_green': 0.548,
   'strokes_gained_total': 0.459,
   'total_driving': 114,
   'all_around_ranking': 44}},
 {'id': '229faa9c-fc01-46bb-a8cb-f6b0310a8cef',
  'first_name': 'Sam',
  'last_name': 'Ryder',
  'country': 'UNITED STATES',
  'abbr_name': 'S.Ryder',
  'statistics': {'events_played': 12,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 2,
   'cuts': 4,
   'cuts_made': 8,
   'withdrawals': 0,
   'points': 138.0,
   'points_rank': 153,
   'earnings': 368375.0,
   'earnings_rank': 155,
   'drive_avg': 299.4,
   'drive_acc': 57.25,
   'gir_pct': 67.84,
   'putt_avg': 1.716,
   'sand_saves_pct': 51.72,
   'birdies_per_round': 3.97,
   'holes_per_eagle': 136.8,
   'world_rank': 283,
   'strokes_gained': 0.445,
   'hole_proximity_avg': '34\' 9"',
   'scrambling_pct': 59.09,
   'scoring_avg': 70.82,
   'strokes_gained_tee_green': 0.116,
   'strokes_gained_total': 0.561,
   'total_driving': 237,
   'all_around_ranking': 48}},
 {'id': '7319e8bc-da2f-40a4-8e28-51ad3b28eb2a',
  'first_name': 'Alejandro',
  'last_name': 'Tosti',
  'country': 'ARGENTINA',
  'abbr_name': 'A.Tosti',
  'statistics': {'events_played': 22,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 0,
   'cuts': 18,
   'cuts_made': 4,
   'withdrawals': 0,
   'points': 54.0,
   'points_rank': 188,
   'earnings': 125412.0,
   'earnings_rank': 192,
   'drive_avg': 313.2,
   'drive_acc': 56.23,
   'gir_pct': 61.87,
   'putt_avg': 1.794,
   'sand_saves_pct': 46.05,
   'birdies_per_round': 3.57,
   'holes_per_eagle': 306.0,
   'world_rank': 493,
   'strokes_gained': -0.862,
   'hole_proximity_avg': '39\' 1"',
   'scrambling_pct': 54.29,
   'scoring_avg': 72.53,
   'strokes_gained_tee_green': -0.735,
   'strokes_gained_total': -1.597,
   'total_driving': 160,
   'all_around_ranking': 152}},
 {'id': '72b7246a-6391-4024-8d0f-35fa1c459664',
  'first_name': 'Cameron',
  'last_name': 'Champ',
  'country': 'UNITED STATES',
  'abbr_name': 'C.Champ',
  'statistics': {'events_played': 8,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 0,
   'top_25': 0,
   'cuts': 4,
   'cuts_made': 3,
   'withdrawals': 1,
   'points': 13.0,
   'points_rank': 201,
   'earnings': 33016.0,
   'earnings_rank': 204,
   'drive_avg': 318.5,
   'drive_acc': 66.79,
   'gir_pct': 69.88,
   'putt_avg': 1.803,
   'sand_saves_pct': 55.88,
   'birdies_per_round': 3.37,
   'holes_per_eagle': 171.0,
   'world_rank': 441,
   'strokes_gained': -0.297,
   'hole_proximity_avg': '37\' 5"',
   'scrambling_pct': 56.31,
   'scoring_avg': 72.133,
   'strokes_gained_tee_green': -0.767,
   'strokes_gained_total': -1.063}},
 {'id': '8169868c-7b2c-45ff-a9fa-4628f463845a',
  'first_name': 'Jackson',
  'last_name': 'Koivun',
  'country': 'UNITED STATES',
  'abbr_name': 'J.Koivun',
  'statistics': {'events_played': 8,
   'first_place': 1,
   'second_place': 0,
   'third_place': 0,
   'top_10': 3,
   'top_25': 5,
   'cuts': 1,
   'cuts_made': 7,
   'withdrawals': 0,
   'points': 730.0,
   'points_rank': 62,
   'earnings': 2140387.0,
   'earnings_rank': 67,
   'drive_avg': 307.5,
   'drive_acc': 73.32,
   'gir_pct': 73.7,
   'putt_avg': 1.749,
   'sand_saves_pct': 50.0,
   'birdies_per_round': 4.2,
   'holes_per_eagle': 135.0,
   'world_rank': 58,
   'strokes_gained': 0.153,
   'hole_proximity_avg': '33\' 4"',
   'scrambling_pct': 63.38,
   'scoring_avg': 68.751,
   'strokes_gained_tee_green': 1.43,
   'strokes_gained_total': 1.583}},
 {'id': '77a9104b-6fd4-40b7-85e2-10b2448a8f86',
  'first_name': 'Kevin',
  'last_name': 'Yu',
  'country': 'CHINESE TAIPEI',
  'abbr_name': 'K.Yu',
  'statistics': {'events_played': 21,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 2,
   'top_25': 6,
   'cuts': 9,
   'cuts_made': 12,
   'withdrawals': 0,
   'points': 472.0,
   'points_rank': 93,
   'earnings': 1357836.0,
   'earnings_rank': 97,
   'drive_avg': 309.7,
   'drive_acc': 61.25,
   'gir_pct': 69.49,
   'putt_avg': 1.726,
   'sand_saves_pct': 54.55,
   'birdies_per_round': 4.38,
   'holes_per_eagle': 106.4,
   'world_rank': 105,
   'strokes_gained': -0.123,
   'hole_proximity_avg': '36\' 10"',
   'scrambling_pct': 58.26,
   'scoring_avg': 70.588,
   'strokes_gained_tee_green': 0.546,
   'strokes_gained_total': 0.424,
   'total_driving': 120,
   'all_around_ranking': 4}},
 {'id': '3888a78e-b24a-4005-8915-2f03fccf3107',
  'first_name': 'Patrick',
  'last_name': 'Rodgers',
  'country': 'UNITED STATES',
  'abbr_name': 'P.Rodgers',
  'statistics': {'events_played': 23,
   'first_place': 0,
   'second_place': 0,
   'third_place': 1,
   'top_10': 1,
   'top_25': 6,
   'cuts': 5,
   'cuts_made': 17,
   'withdrawals': 1,
   'points': 657.0,
   'points_rank': 67,
   'earnings': 2538290.0,
   'earnings_rank': 62,
   'drive_avg': 308.4,
   'drive_acc': 54.45,
   'gir_pct': 63.08,
   'putt_avg': 1.742,
   'sand_saves_pct': 48.28,
   'birdies_per_round': 3.75,
   'holes_per_eagle': 129.3,
   'world_rank': 107,
   'strokes_gained': 0.228,
   'hole_proximity_avg': '38\' 7"',
   'scrambling_pct': 56.57,
   'scoring_avg': 71.326,
   'strokes_gained_tee_green': -0.487,
   'strokes_gained_total': -0.259,
   'total_driving': 199,
   'all_around_ranking': 117}},
 {'id': '1f1e519b-a51a-4de5-8ce7-ce882772c194',
  'first_name': 'Neal',
  'last_name': 'Shipley',
  'country': 'UNITED STATES',
  'abbr_name': 'N.Shipley',
  'statistics': {'events_played': 21,
   'first_place': 0,
   'second_place': 0,
   'third_place': 1,
   'top_10': 1,
   'top_25': 1,
   'cuts': 12,
   'cuts_made': 9,
   'withdrawals': 0,
   'points': 222.0,
   'points_rank': 135,
   'earnings': 507501.0,
   'earnings_rank': 145,
   'drive_avg': 310.2,
   'drive_acc': 68.83,
   'gir_pct': 68.64,
   'putt_avg': 1.787,
   'sand_saves_pct': 38.46,
   'birdies_per_round': 3.54,
   'holes_per_eagle': 132.8,
   'world_rank': 166,
   'strokes_gained': -0.367,
   'hole_proximity_avg': '35\' 6"',
   'scrambling_pct': 59.16,
   'scoring_avg': 71.059,
   'strokes_gained_tee_green': 0.157,
   'strokes_gained_total': -0.21,
   'total_driving': 62,
   'all_around_ranking': 102}},
 {'id': '6577ec3d-9e78-4979-8f4c-01c465fa6b1d',
  'first_name': 'Tommy',
  'last_name': 'Fleetwood',
  'country': 'ENGLAND',
  'abbr_name': 'T.Fleetwood',
  'statistics': {'events_played': 19,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 8,
   'top_25': 14,
   'cuts': 1,
   'cuts_made': 18,
   'withdrawals': 0,
   'points': 2263.0,
   'points_rank': 11,
   'earnings': 7714605.0,
   'earnings_rank': 17,
   'drive_avg': 304.8,
   'drive_acc': 67.83,
   'gir_pct': 66.97,
   'putt_avg': 1.734,
   'sand_saves_pct': 57.02,
   'birdies_per_round': 3.74,
   'holes_per_eagle': 95.1,
   'world_rank': 9,
   'strokes_gained': 0.065,
   'hole_proximity_avg': '37\' 1"',
   'scrambling_pct': 65.45,
   'scoring_avg': 69.71,
   'strokes_gained_tee_green': 1.111,
   'strokes_gained_total': 1.176,
   'total_driving': 115,
   'all_around_ranking': 13}},
 {'id': 'c9466b3a-d8f6-42ec-aa53-1f55db13377d',
  'first_name': 'Jacob',
  'last_name': 'Bridgeman',
  'country': 'UNITED STATES',
  'abbr_name': 'J.Bridgeman',
  'statistics': {'events_played': 24,
   'first_place': 2,
   'second_place': 0,
   'third_place': 0,
   'top_10': 7,
   'top_25': 12,
   'cuts': 1,
   'cuts_made': 23,
   'withdrawals': 0,
   'points': 1961.0,
   'points_rank': 4,
   'earnings': 10885508.0,
   'earnings_rank': 7,
   'drive_avg': 305.9,
   'drive_acc': 63.61,
   'gir_pct': 66.55,
   'putt_avg': 1.693,
   'sand_saves_pct': 43.79,
   'birdies_per_round': 4.38,
   'holes_per_eagle': 211.5,
   'world_rank': 20,
   'strokes_gained': 0.757,
   'hole_proximity_avg': '36\' 7"',
   'scrambling_pct': 62.9,
   'scoring_avg': 69.856,
   'strokes_gained_tee_green': 0.32,
   'strokes_gained_total': 1.077,
   'total_driving': 127,
   'all_around_ranking': 32}},
 {'id': 'd45bcf4a-5803-4b0b-ab6c-6427a76cecf7',
  'first_name': 'Hideki',
  'last_name': 'Matsuyama',
  'country': 'JAPAN',
  'abbr_name': 'H.Matsuyama',
  'statistics': {'events_played': 23,
   'first_place': 0,
   'second_place': 1,
   'third_place': 1,
   'top_10': 6,
   'top_25': 14,
   'cuts': 0,
   'cuts_made': 23,
   'withdrawals': 0,
   'points': 1637.0,
   'points_rank': 21,
   'earnings': 6088207.0,
   'earnings_rank': 23,
   'drive_avg': 304.1,
   'drive_acc': 61.72,
   'gir_pct': 66.06,
   'putt_avg': 1.743,
   'sand_saves_pct': 58.71,
   'birdies_per_round': 4.08,
   'holes_per_eagle': 207.0,
   'world_rank': 27,
   'strokes_gained': -0.013,
   'hole_proximity_avg': '35\' 6"',
   'scrambling_pct': 64.41,
   'scoring_avg': 69.978,
   'strokes_gained_tee_green': 0.772,
   'strokes_gained_total': 0.759,
   'total_driving': 158,
   'all_around_ranking': 34}},
 {'id': 'dfbe6c98-2862-4266-a5e4-494003349a31',
  'first_name': 'Akshay',
  'last_name': 'Bhatia',
  'country': 'UNITED STATES',
  'abbr_name': 'A.Bhatia',
  'statistics': {'events_played': 21,
   'first_place': 1,
   'second_place': 0,
   'third_place': 1,
   'top_10': 4,
   'top_25': 11,
   'cuts': 7,
   'cuts_made': 14,
   'withdrawals': 0,
   'points': 1842.0,
   'points_rank': 18,
   'earnings': 8401049.0,
   'earnings_rank': 14,
   'drive_avg': 304.1,
   'drive_acc': 56.14,
   'gir_pct': 64.55,
   'putt_avg': 1.71,
   'sand_saves_pct': 65.41,
   'birdies_per_round': 4.06,
   'holes_per_eagle': 182.6,
   'world_rank': 35,
   'strokes_gained': 0.483,
   'hole_proximity_avg': '36\' 0"',
   'scrambling_pct': 61.15,
   'scoring_avg': 70.437,
   'strokes_gained_tee_green': 0.161,
   'strokes_gained_total': 0.644,
   'total_driving': 231,
   'all_around_ranking': 49}},
 {'id': 'fa3c656a-7f3e-4931-ab19-5e07cc52c4f9',
  'first_name': 'Alex',
  'last_name': 'Smalley',
  'country': 'UNITED STATES',
  'abbr_name': 'A.Smalley',
  'statistics': {'events_played': 24,
   'first_place': 0,
   'second_place': 2,
   'third_place': 1,
   'top_10': 5,
   'top_25': 12,
   'cuts': 4,
   'cuts_made': 20,
   'withdrawals': 0,
   'points': 1443.0,
   'points_rank': 27,
   'earnings': 5800908.0,
   'earnings_rank': 25,
   'drive_avg': 308.1,
   'drive_acc': 60.89,
   'gir_pct': 69.97,
   'putt_avg': 1.756,
   'sand_saves_pct': 53.45,
   'birdies_per_round': 3.9,
   'holes_per_eagle': 189.0,
   'world_rank': 46,
   'strokes_gained': 0.123,
   'hole_proximity_avg': '35\' 7"',
   'scrambling_pct': 59.69,
   'scoring_avg': 70.198,
   'strokes_gained_tee_green': 0.509,
   'strokes_gained_total': 0.632,
   'total_driving': 136,
   'all_around_ranking': 33}},
 {'id': '2094fa02-6411-48df-a717-aa1a7228d645',
  'first_name': 'Justin',
  'last_name': 'Thomas',
  'country': 'UNITED STATES',
  'abbr_name': 'J.Thomas',
  'statistics': {'events_played': 17,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 2,
   'top_25': 10,
   'cuts': 1,
   'cuts_made': 16,
   'withdrawals': 0,
   'points': 1096.0,
   'points_rank': 43,
   'earnings': 3966774.0,
   'earnings_rank': 42,
   'drive_avg': 311.3,
   'drive_acc': 61.03,
   'gir_pct': 63.55,
   'putt_avg': 1.74,
   'sand_saves_pct': 60.17,
   'birdies_per_round': 3.77,
   'holes_per_eagle': 198.0,
   'world_rank': 26,
   'strokes_gained': -0.015,
   'hole_proximity_avg': '38\' 7"',
   'scrambling_pct': 59.82,
   'scoring_avg': 70.138,
   'strokes_gained_tee_green': 0.688,
   'strokes_gained_total': 0.673,
   'total_driving': 115,
   'all_around_ranking': 51}},
 {'id': 'f33d746b-8e14-4325-a4e1-81d6f983b163',
  'first_name': 'Tony',
  'last_name': 'Finau',
  'country': 'UNITED STATES',
  'abbr_name': 'T.Finau',
  'statistics': {'events_played': 23,
   'first_place': 0,
   'second_place': 0,
   'third_place': 0,
   'top_10': 1,
   'top_25': 4,
   'cuts': 7,
   'cuts_made': 16,
   'withdrawals': 0,
   'points': 416.0,
   'points_rank': 100,
   'earnings': 1621910.0,
   'earnings_rank': 86,
   'drive_avg': 311.8,
   'drive_acc': 54.21,
   'gir_pct': 63.71,
   'putt_avg': 1.728,
   'sand_saves_pct': 55.56,
   'birdies_per_round': 3.96,
   'holes_per_eagle': 126.0,
   'world_rank': 151,
   'strokes_gained': -0.257,
   'hole_proximity_avg': '37\' 4"',
   'scrambling_pct': 59.44,
   'scoring_avg': 71.239,
   'strokes_gained_tee_green': -0.026,
   'strokes_gained_total': -0.283,

In [10]:
formatted_players_list = json.dumps(players_list, indent=4)
print(formatted_players_list)

[
    {
        "id": "da226913-b804-48de-adbf-96e956eb75ac",
        "first_name": "Rory",
        "last_name": "McIlroy",
        "country": "NORTHERN IRELAND",
        "abbr_name": "R.McIlroy",
        "statistics": {
            "events_played": 14,
            "first_place": 1,
            "second_place": 1,
            "third_place": 1,
            "top_10": 6,
            "top_25": 9,
            "cuts": 0,
            "cuts_made": 14,
            "withdrawals": 1,
            "points": 2095.0,
            "points_rank": 4,
            "earnings": 11573749.0,
            "earnings_rank": 5,
            "drive_avg": 330.3,
            "drive_acc": 54.65,
            "gir_pct": 68.62,
            "putt_avg": 1.739,
            "sand_saves_pct": 56.04,
            "birdies_per_round": 4.31,
            "holes_per_eagle": 138.9,
            "world_rank": 2,
            "strokes_gained": 0.243,
            "hole_proximity_avg": "36' 11\"",
            "scrambling_pct": 59.34,
            "scoring_avg": 69.342,
            "strokes_gained_tee_green": 1.098,
            "strokes_gained_total": 1.341,
            "total_driving": 137,
            "all_around_ranking": 7
        }
    },
    {
        "id": "da8b4888-9330-46d0-8f8a-f76fae949dba",
        "first_name": "Jackson",
        "last_name": "Suber",
        "country": "UNITED STATES",
        "abbr_name": "J.Suber",
        "statistics": {
            "events_played": 20,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 3,
            "top_25": 6,
            "cuts": 7,
            "cuts_made": 13,
            "withdrawals": 0,
            "points": 554.0,
            "points_rank": 74,
            "earnings": 1782277.0,
            "earnings_rank": 78,
            "drive_avg": 306.2,
            "drive_acc": 60.78,
            "gir_pct": 70.68,
            "putt_avg": 1.776,
            "sand_saves_pct": 54.55,
            "birdies_per_round": 4.18,
            "holes_per_eagle": 146.3,
            "world_rank": 94,
            "strokes_gained": -0.291,
            "hole_proximity_avg": "33' 6\"",
            "scrambling_pct": 61.52,
            "scoring_avg": 70.31,
            "strokes_gained_tee_green": 0.767,
            "strokes_gained_total": 0.475,
            "total_driving": 158,
            "all_around_ranking": 24
        }
    },
    {
        "id": "7a4b2b40-4675-41d9-86fd-cc6a61a1d3b2",
        "first_name": "Nicolai",
        "last_name": "H\u00f8jgaard",
        "country": "DENMARK",
        "abbr_name": "N.H\u00f8jgaard",
        "statistics": {
            "events_played": 21,
            "first_place": 0,
            "second_place": 2,
            "third_place": 1,
            "top_10": 4,
            "top_25": 8,
            "cuts": 5,
            "cuts_made": 16,
            "withdrawals": 0,
            "points": 1228.0,
            "points_rank": 35,
            "earnings": 4914868.0,
            "earnings_rank": 35,
            "drive_avg": 325.1,
            "drive_acc": 52.64,
            "gir_pct": 65.39,
            "putt_avg": 1.749,
            "sand_saves_pct": 50.0,
            "birdies_per_round": 3.68,
            "holes_per_eagle": 88.8,
            "world_rank": 42,
            "strokes_gained": 0.099,
            "hole_proximity_avg": "37' 6\"",
            "scrambling_pct": 60.52,
            "scoring_avg": 70.168,
            "strokes_gained_tee_green": 0.592,
            "strokes_gained_total": 0.691,
            "total_driving": 155,
            "all_around_ranking": 68
        }
    },
    {
        "id": "a9053c60-3cc0-48cb-bcf2-4848963f352d",
        "first_name": "Kris",
        "last_name": "Ventura",
        "country": "NORWAY",
        "abbr_name": "K.Ventura",
        "statistics": {
            "events_played": 19,
            "first_place": 0,
            "second_place": 1,
            "third_place": 0,
            "top_10": 3,
            "top_25": 5,
            "cuts": 12,
            "cuts_made": 7,
            "withdrawals": 0,
            "points": 373.0,
            "points_rank": 107,
            "earnings": 1180422.0,
            "earnings_rank": 105,
            "drive_avg": 312.8,
            "drive_acc": 63.24,
            "gir_pct": 69.73,
            "putt_avg": 1.774,
            "sand_saves_pct": 53.85,
            "birdies_per_round": 3.53,
            "holes_per_eagle": 63.0,
            "world_rank": 195,
            "strokes_gained": -0.03,
            "hole_proximity_avg": "34' 3\"",
            "scrambling_pct": 62.17,
            "scoring_avg": 70.693,
            "strokes_gained_tee_green": 0.225,
            "strokes_gained_total": 0.195,
            "total_driving": 77,
            "all_around_ranking": 35
        }
    },
    {
        "id": "9b625995-cfb6-4ae6-91bb-b736b7d56bf7",
        "first_name": "Gordon",
        "last_name": "Sargent",
        "country": "UNITED STATES",
        "abbr_name": "G.Sargent",
        "statistics": {
            "events_played": 18,
            "first_place": 0,
            "second_place": 1,
            "third_place": 0,
            "top_10": 2,
            "top_25": 3,
            "cuts": 11,
            "cuts_made": 7,
            "withdrawals": 0,
            "points": 232.0,
            "points_rank": 132,
            "earnings": 599780.0,
            "earnings_rank": 136,
            "drive_avg": 320.1,
            "drive_acc": 60.15,
            "gir_pct": 66.31,
            "putt_avg": 1.759,
            "sand_saves_pct": 51.61,
            "birdies_per_round": 4.04,
            "holes_per_eagle": 169.2,
            "world_rank": 331,
            "strokes_gained": -0.209,
            "hole_proximity_avg": "42' 3\"",
            "scrambling_pct": 55.79,
            "scoring_avg": 71.602,
            "strokes_gained_tee_green": -0.486,
            "strokes_gained_total": -0.694,
            "total_driving": 98,
            "all_around_ranking": 80
        }
    },
    {
        "id": "606d1a25-2e9a-4e9f-95a2-c0947bb52912",
        "first_name": "Rasmus",
        "last_name": "Neergaard-Petersen",
        "country": "DENMARK",
        "abbr_name": "R.Neergaard-Petersen",
        "statistics": {
            "events_played": 18,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 2,
            "top_25": 4,
            "cuts": 5,
            "cuts_made": 13,
            "withdrawals": 0,
            "points": 404.0,
            "points_rank": 102,
            "earnings": 1098718.0,
            "earnings_rank": 111,
            "drive_avg": 308.4,
            "drive_acc": 62.09,
            "gir_pct": 67.24,
            "putt_avg": 1.792,
            "sand_saves_pct": 31.76,
            "birdies_per_round": 3.5,
            "holes_per_eagle": 104.4,
            "world_rank": 72,
            "strokes_gained": 0.032,
            "hole_proximity_avg": "38' 7\"",
            "scrambling_pct": 57.02,
            "scoring_avg": 70.54,
            "strokes_gained_tee_green": 0.212,
            "strokes_gained_total": 0.244,
            "total_driving": 111,
            "all_around_ranking": 105
        }
    },
    {
        "id": "cb867fe8-660d-43de-9486-c80cc0837190",
        "first_name": "Henrik",
        "last_name": "Norlander",
        "country": "SWEDEN",
        "abbr_name": "H.Norlander",
        "statistics": {
            "events_played": 7,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 0,
            "cuts": 5,
            "cuts_made": 2,
            "withdrawals": 0,
            "points": 6.0,
            "points_rank": 206,
            "earnings": 28015.0,
            "earnings_rank": 206,
            "drive_avg": 281.4,
            "drive_acc": 61.01,
            "gir_pct": 59.72,
            "putt_avg": 1.75,
            "sand_saves_pct": 50.0,
            "birdies_per_round": 3.25,
            "holes_per_eagle": 144.0,
            "world_rank": 561,
            "strokes_gained": -0.484,
            "hole_proximity_avg": "37' 7\"",
            "scrambling_pct": 52.59,
            "scoring_avg": 72.854,
            "strokes_gained_tee_green": -1.357,
            "strokes_gained_total": -1.842
        }
    },
    {
        "id": "17d9be3d-a0a4-4a8c-a2ac-d127050f42c0",
        "first_name": "Fabi\u00e1n",
        "last_name": "G\u00f3mez",
        "country": "ARGENTINA",
        "abbr_name": "F.G\u00f3mez",
        "statistics": {
            "events_played": 7,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 0,
            "cuts": 2,
            "cuts_made": 5,
            "withdrawals": 0,
            "points": 25.0,
            "points_rank": 199,
            "earnings": 85851.0,
            "earnings_rank": 198,
            "drive_avg": 292.4,
            "drive_acc": 75.15,
            "gir_pct": 67.36,
            "putt_avg": 1.749,
            "sand_saves_pct": 53.66,
            "birdies_per_round": 4.08,
            "holes_per_eagle": 432.0,
            "world_rank": 445,
            "strokes_gained": -0.57,
            "hole_proximity_avg": "37' 3\"",
            "scrambling_pct": 62.41,
            "scoring_avg": 71.825,
            "strokes_gained_tee_green": -0.128,
            "strokes_gained_total": -0.698
        }
    },
    {
        "id": "0b5d3fd6-e3ec-4efd-8743-60db44c87425",
        "first_name": "Keegan",
        "last_name": "Bradley",
        "country": "UNITED STATES",
        "abbr_name": "K.Bradley",
        "statistics": {
            "events_played": 20,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 6,
            "cuts": 4,
            "cuts_made": 16,
            "withdrawals": 0,
            "points": 548.0,
            "points_rank": 77,
            "earnings": 2225547.0,
            "earnings_rank": 66,
            "drive_avg": 311.6,
            "drive_acc": 60.96,
            "gir_pct": 66.59,
            "putt_avg": 1.764,
            "sand_saves_pct": 52.46,
            "birdies_per_round": 3.82,
            "holes_per_eagle": 99.7,
            "world_rank": 50,
            "strokes_gained": -0.089,
            "hole_proximity_avg": "36' 1\"",
            "scrambling_pct": 57.27,
            "scoring_avg": 70.556,
            "strokes_gained_tee_green": 0.548,
            "strokes_gained_total": 0.459,
            "total_driving": 114,
            "all_around_ranking": 44
        }
    },
    {
        "id": "229faa9c-fc01-46bb-a8cb-f6b0310a8cef",
        "first_name": "Sam",
        "last_name": "Ryder",
        "country": "UNITED STATES",
        "abbr_name": "S.Ryder",
        "statistics": {
            "events_played": 12,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 2,
            "cuts": 4,
            "cuts_made": 8,
            "withdrawals": 0,
            "points": 138.0,
            "points_rank": 153,
            "earnings": 368375.0,
            "earnings_rank": 155,
            "drive_avg": 299.4,
            "drive_acc": 57.25,
            "gir_pct": 67.84,
            "putt_avg": 1.716,
            "sand_saves_pct": 51.72,
            "birdies_per_round": 3.97,
            "holes_per_eagle": 136.8,
            "world_rank": 283,
            "strokes_gained": 0.445,
            "hole_proximity_avg": "34' 9\"",
            "scrambling_pct": 59.09,
            "scoring_avg": 70.82,
            "strokes_gained_tee_green": 0.116,
            "strokes_gained_total": 0.561,
            "total_driving": 237,
            "all_around_ranking": 48
        }
    },
    {
        "id": "7319e8bc-da2f-40a4-8e28-51ad3b28eb2a",
        "first_name": "Alejandro",
        "last_name": "Tosti",
        "country": "ARGENTINA",
        "abbr_name": "A.Tosti",
        "statistics": {
            "events_played": 22,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 0,
            "cuts": 18,
            "cuts_made": 4,
            "withdrawals": 0,
            "points": 54.0,
            "points_rank": 188,
            "earnings": 125412.0,
            "earnings_rank": 192,
            "drive_avg": 313.2,
            "drive_acc": 56.23,
            "gir_pct": 61.87,
            "putt_avg": 1.794,
            "sand_saves_pct": 46.05,
            "birdies_per_round": 3.57,
            "holes_per_eagle": 306.0,
            "world_rank": 493,
            "strokes_gained": -0.862,
            "hole_proximity_avg": "39' 1\"",
            "scrambling_pct": 54.29,
            "scoring_avg": 72.53,
            "strokes_gained_tee_green": -0.735,
            "strokes_gained_total": -1.597,
            "total_driving": 160,
            "all_around_ranking": 152
        }
    },
    {
        "id": "72b7246a-6391-4024-8d0f-35fa1c459664",
        "first_name": "Cameron",
        "last_name": "Champ",
        "country": "UNITED STATES",
        "abbr_name": "C.Champ",
        "statistics": {
            "events_played": 8,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 0,
            "top_25": 0,
            "cuts": 4,
            "cuts_made": 3,
            "withdrawals": 1,
            "points": 13.0,
            "points_rank": 201,
            "earnings": 33016.0,
            "earnings_rank": 204,
            "drive_avg": 318.5,
            "drive_acc": 66.79,
            "gir_pct": 69.88,
            "putt_avg": 1.803,
            "sand_saves_pct": 55.88,
            "birdies_per_round": 3.37,
            "holes_per_eagle": 171.0,
            "world_rank": 441,
            "strokes_gained": -0.297,
            "hole_proximity_avg": "37' 5\"",
            "scrambling_pct": 56.31,
            "scoring_avg": 72.133,
            "strokes_gained_tee_green": -0.767,
            "strokes_gained_total": -1.063
        }
    },
    {
        "id": "8169868c-7b2c-45ff-a9fa-4628f463845a",
        "first_name": "Jackson",
        "last_name": "Koivun",
        "country": "UNITED STATES",
        "abbr_name": "J.Koivun",
        "statistics": {
            "events_played": 8,
            "first_place": 1,
            "second_place": 0,
            "third_place": 0,
            "top_10": 3,
            "top_25": 5,
            "cuts": 1,
            "cuts_made": 7,
            "withdrawals": 0,
            "points": 730.0,
            "points_rank": 62,
            "earnings": 2140387.0,
            "earnings_rank": 67,
            "drive_avg": 307.5,
            "drive_acc": 73.32,
            "gir_pct": 73.7,
            "putt_avg": 1.749,
            "sand_saves_pct": 50.0,
            "birdies_per_round": 4.2,
            "holes_per_eagle": 135.0,
            "world_rank": 58,
            "strokes_gained": 0.153,
            "hole_proximity_avg": "33' 4\"",
            "scrambling_pct": 63.38,
            "scoring_avg": 68.751,
            "strokes_gained_tee_green": 1.43,
            "strokes_gained_total": 1.583
        }
    },
    {
        "id": "77a9104b-6fd4-40b7-85e2-10b2448a8f86",
        "first_name": "Kevin",
        "last_name": "Yu",
        "country": "CHINESE TAIPEI",
        "abbr_name": "K.Yu",
        "statistics": {
            "events_played": 21,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 2,
            "top_25": 6,
            "cuts": 9,
            "cuts_made": 12,
            "withdrawals": 0,
            "points": 472.0,
            "points_rank": 93,
            "earnings": 1357836.0,
            "earnings_rank": 97,
            "drive_avg": 309.7,
            "drive_acc": 61.25,
            "gir_pct": 69.49,
            "putt_avg": 1.726,
            "sand_saves_pct": 54.55,
            "birdies_per_round": 4.38,
            "holes_per_eagle": 106.4,
            "world_rank": 105,
            "strokes_gained": -0.123,
            "hole_proximity_avg": "36' 10\"",
            "scrambling_pct": 58.26,
            "scoring_avg": 70.588,
            "strokes_gained_tee_green": 0.546,
            "strokes_gained_total": 0.424,
            "total_driving": 120,
            "all_around_ranking": 4
        }
    },
    {
        "id": "3888a78e-b24a-4005-8915-2f03fccf3107",
        "first_name": "Patrick",
        "last_name": "Rodgers",
        "country": "UNITED STATES",
        "abbr_name": "P.Rodgers",
        "statistics": {
            "events_played": 23,
            "first_place": 0,
            "second_place": 0,
            "third_place": 1,
            "top_10": 1,
            "top_25": 6,
            "cuts": 5,
            "cuts_made": 17,
            "withdrawals": 1,
            "points": 657.0,
            "points_rank": 67,
            "earnings": 2538290.0,
            "earnings_rank": 62,
            "drive_avg": 308.4,
            "drive_acc": 54.45,
            "gir_pct": 63.08,
            "putt_avg": 1.742,
            "sand_saves_pct": 48.28,
            "birdies_per_round": 3.75,
            "holes_per_eagle": 129.3,
            "world_rank": 107,
            "strokes_gained": 0.228,
            "hole_proximity_avg": "38' 7\"",
            "scrambling_pct": 56.57,
            "scoring_avg": 71.326,
            "strokes_gained_tee_green": -0.487,
            "strokes_gained_total": -0.259,
            "total_driving": 199,
            "all_around_ranking": 117
        }
    },
    {
        "id": "1f1e519b-a51a-4de5-8ce7-ce882772c194",
        "first_name": "Neal",
        "last_name": "Shipley",
        "country": "UNITED STATES",
        "abbr_name": "N.Shipley",
        "statistics": {
            "events_played": 21,
            "first_place": 0,
            "second_place": 0,
            "third_place": 1,
            "top_10": 1,
            "top_25": 1,
            "cuts": 12,
            "cuts_made": 9,
            "withdrawals": 0,
            "points": 222.0,
            "points_rank": 135,
            "earnings": 507501.0,
            "earnings_rank": 145,
            "drive_avg": 310.2,
            "drive_acc": 68.83,
            "gir_pct": 68.64,
            "putt_avg": 1.787,
            "sand_saves_pct": 38.46,
            "birdies_per_round": 3.54,
            "holes_per_eagle": 132.8,
            "world_rank": 166,
            "strokes_gained": -0.367,
            "hole_proximity_avg": "35' 6\"",
            "scrambling_pct": 59.16,
            "scoring_avg": 71.059,
            "strokes_gained_tee_green": 0.157,
            "strokes_gained_total": -0.21,
            "total_driving": 62,
            "all_around_ranking": 102
        }
    },
    {
        "id": "6577ec3d-9e78-4979-8f4c-01c465fa6b1d",
        "first_name": "Tommy",
        "last_name": "Fleetwood",
        "country": "ENGLAND",
        "abbr_name": "T.Fleetwood",
        "statistics": {
            "events_played": 19,
            "first_place": 0,
            "second_place": 0,
            "third_place": 0,
            "top_10": 8,
            "top_25": 14,
            "cuts": 1,
            "cuts_made": 18,
            "withdrawals": 0,
            "points": 2263.0,
            "points_rank": 11,
            "earnings": 7714605.0,
            "earnings_rank": 17,
            "drive_avg": 304.8,
            "drive_acc": 67.83,
            "gir_pct": 66.97,
            "putt_avg": 1.734,
            "sand_saves_pct": 57.02,
            "birdies_per_round": 3.74,
            "holes_per_eagle": 95.1,
            "world_rank": 9,
            "strokes_gained": 0.065,
            "hole_proximity_avg": "37' 1\"",
            "scrambling_pct": 65.45,
            "scoring_avg": 69.71,

In [ ]:
McIlroy_wins = players_list[0]["statistics"]["first_place"]
print(McIlroy_wins)

1

In [12]:
rows = []
column_names = ['first_name', 'last_name', 'country', 'world_rank', 'events_played', 'first_place', 'second_place', 'top_10', 'top_25', 'cuts_made', 'fed_ex_rank', 'strokes_gained_total']

for player in players_list:
    first_name              = player['first_name']
    last_name               = player['last_name']
    country                 = player['country']
    world_rank              = player['statistics']['world_rank']
    points_rank             = player['statistics']['points_rank']
    events_played           = player['statistics']['events_played']
    first_place             = player['statistics']['first_place']
    second_place            = player['statistics']['second_place']
    top_10                  = player['statistics']['top_10']
    top_25                  = player['statistics']['top_25']
    cuts_made               = player['statistics']['cuts_made']
    FedEx_rank              = player['statistics']['points_rank']
    strokes_gained_total    = player['statistics']['strokes_gained_total']

    tuple_of_player_data = (first_name, last_name, country, world_rank, events_played, first_place, second_place, top_10, top_25, cuts_made, FedEx_rank, strokes_gained_total)

    rows.append(tuple_of_player_data)

In [13]:
print(rows)

[('Rory', 'McIlroy', 'NORTHERN IRELAND', 2, 14, 1, 1, 6, 9, 14, 4, 1.341), ('Jackson', 'Suber', 'UNITED STATES', 94, 20, 0, 0, 3, 6, 13, 74, 0.475), ('Nicolai', 'Højgaard', 'DENMARK', 42, 21, 0, 2, 4, 8, 16, 35, 0.691), ('Kris', 'Ventura', 'NORWAY', 195, 19, 0, 1, 3, 5, 7, 107, 0.195), ('Gordon', 'Sargent', 'UNITED STATES', 331, 18, 0, 1, 2, 3, 7, 132, -0.694), ('Rasmus', 'Neergaard-Petersen', 'DENMARK', 72, 18, 0, 0, 2, 4, 13, 102, 0.244), ('Henrik', 'Norlander', 'SWEDEN', 561, 7, 0, 0, 0, 0, 2, 206, -1.842), ('Fabián', 'Gómez', 'ARGENTINA', 445, 7, 0, 0, 0, 0, 5, 199, -0.698), ('Keegan', 'Bradley', 'UNITED STATES', 50, 20, 0, 0, 0, 6, 16, 77, 0.459), ('Sam', 'Ryder', 'UNITED STATES', 283, 12, 0, 0, 0, 2, 8, 153, 0.561), ('Alejandro', 'Tosti', 'ARGENTINA', 493, 22, 0, 0, 0, 0, 4, 188, -1.597), ('Cameron', 'Champ', 'UNITED STATES', 441, 8, 0, 0, 0, 0, 3, 201, -1.063), ('Jackson', 'Koivun', 'UNITED STATES', 58, 8, 1, 0, 3, 5, 7, 62, 1.583), ('Kevin', 'Yu', 'CHINESE TAIPEI', 105, 21, 0, 0, 2, 6, 12, 93, 0.424), ('Patrick', 'Rodgers', 'UNITED STATES', 107, 23, 0, 0, 1, 6, 17, 67, -0.259), ('Neal', 'Shipley', 'UNITED STATES', 166, 21, 0, 0, 1, 1, 9, 135, -0.21), ('Tommy', 'Fleetwood', 'ENGLAND', 9, 19, 0, 0, 8, 14, 18, 11, 1.176), ('Jacob', 'Bridgeman', 'UNITED STATES', 20, 24, 2, 0, 7, 12, 23, 4, 1.077), ('Hideki', 'Matsuyama', 'JAPAN', 27, 23, 0, 1, 6, 14, 23, 21, 0.759), ('Akshay', 'Bhatia', 'UNITED STATES', 35, 21, 1, 0, 4, 11, 14, 18, 0.644), ('Alex', 'Smalley', 'UNITED STATES', 46, 24, 0, 2, 5, 12, 20, 27, 0.632), ('Justin', 'Thomas', 'UNITED STATES', 26, 17, 0, 0, 2, 10, 16, 43, 0.673), ('Tony', 'Finau', 'UNITED STATES', 151, 23, 0, 0, 1, 4, 16, 100, -0.283), ('Patton', 'Kizzire', 'UNITED STATES', 541, 19, 0, 0, 0, 2, 6, 163, -1.186), ('Adam', 'Schenk', 'UNITED STATES', 218, 23, 0, 0, 0, 1, 8, 160, -1.213), ('Bud', 'Cauley', 'UNITED STATES', 47, 22, 1, 0, 2, 9, 19, 34, 0.265), ('Mac', 'Meissner', 'UNITED STATES', 88, 22, 0, 0, 4, 5, 15, 78, 0.537), ('Jake', 'Knapp', 'UNITED STATES', 51, 17, 0, 0, 6, 9, 12, 38, 0.835), ('Lucas', 'Glover', 'UNITED STATES', 124, 21, 0, 0, 2, 4, 12, 103, -0.724), ('Max', 'Greyserman', 'UNITED STATES', 87, 24, 0, 0, 2, 5, 14, 97, 0.134), ('Chad', 'Ramey', 'UNITED STATES', 200, 22, 0, 0, 0, 2, 15, 129, -0.081), ('James', 'Hahn', 'UNITED STATES', 995, 4, 0, 0, 0, 0, 1, 216, -2.355), ('Denny', 'McCarthy', 'UNITED STATES', 97, 23, 0, 0, 1, 3, 17, 92, 0.063), ('Matt', 'Fitzpatrick', 'ENGLAND', 4, 21, 3, 2, 8, 15, 20, 21, 1.359), ('William', 'Mouw', 'UNITED STATES', 147, 21, 0, 0, 2, 4, 13, 119, -0.086), ('Patrick', 'Cantlay', 'UNITED STATES', 28, 20, 0, 1, 5, 12, 16, 21, 1.01), ('Rasmus', 'Højgaard', 'DENMARK', 75, 19, 0, 0, 2, 4, 13, 110, 0.416), ('Ben', 'Silverman', 'CANADA', 265, 14, 0, 0, 1, 3, 6, 138, 0.237), ('Harris', 'English', 'UNITED STATES', 45, 21, 0, 0, 1, 9, 16, 55, 0.431), ('Kristoffer', 'Reitan', 'NORWAY', 30, 22, 1, 1, 4, 10, 17, 25, 0.091), ('Aaron', 'Rai', 'ENGLAND', 16, 19, 1, 0, 2, 7, 14, 39, 0.463), ('Kevin', 'Roy', 'UNITED STATES', 115, 22, 0, 0, 1, 7, 17, 87, 0.341), ('Sudarshan', 'Yellamaraju', 'CANADA', 108, 23, 0, 0, 3, 7, 16, 59, 0.492), ('Camilo', 'Villegas', 'COLOMBIA', 549, 16, 0, 0, 0, 0, 7, 195, -0.543), ('Jimmy', 'Stanger', 'UNITED STATES', 363, 19, 0, 0, 1, 1, 7, 141, -0.58), ('Michael', 'Thorbjornsen', 'UNITED STATES', 41, 22, 1, 0, 3, 8, 16, 44, 0.315), ('Robert', 'Streb', 'UNITED STATES', 973, 8, 0, 0, 0, 0, 2, 210, -2.187), ('Ben', 'Kohles', 'UNITED STATES', 95, 13, 0, 0, 2, 6, 11, 90, 1.274), ('Austin', 'Cook', 'UNITED STATES', 934, 6, 0, 0, 0, 0, 1, 212, -0.864), ('Nick', 'Hardy', 'UNITED STATES', 660, 12, 0, 0, 0, 2, 3, 194, -0.661), ('Cameron', 'Young', 'UNITED STATES', 3, 20, 2, 1, 8, 11, 20, 11, 0.933), ('Garrick', 'Higgo', 'SOUTH AFRICA', 134, 20, 0, 0, 0, 1, 8, 171, -0.988), ('Max', 'McGreevy', 'UNITED STATES', 131, 25, 0, 0, 0, 2, 13, 125, 0.122), ('Max', 'Homa', 'UNITED STATES', 74, 20, 0, 1, 2, 6, 15, 53, 0.072), ('Andrew', 'Novak', 'UNITED STATES', 83, 25, 0, 0, 3, 7, 16, 81, -0.018), ('Will', 'Gordon', 'UNITED STATES', 399, 7, 0, 0, 1, 1, 4, 177, 0.052), ('Rafael', 'Campos', 'PUERTO RICO', 642, 20, 0, 0, 0, 3, 5, 166, -1.272), ('Luke', 'Donald', 'ENGLAND', 0, 1, 0, 0, 0, 0, 1, 208, -0.38), ('Daniel', 'Brown', 'ENGLAND', 135, 16, 0, 0, 0, 3, 7, 144, -0.313), ('Sungjae', 'Im', 'SOUTH KOREA', 60, 22, 0, 0, 5, 8, 16, 37, 0.356), ('Hank', 'Lebioda', 'UNITED STATES', 281, 21, 0, 0, 1, 3, 12, 140, -0.435), ('Luke', 'List', 'UNITED STATES', 577, 10, 0, 0, 0, 1, 3, 192, -0.665), ('Cameron', 'Davis', 'AUSTRALIA', 395, 17, 0, 0, 0, 1, 5, 190, -1.881), ('Jason', 'Day', 'AUSTRALIA', 71, 17, 0, 1, 2, 4, 11, 85, -0.174), ('Sam', 'Burns', 'UNITED STATES', 8, 20, 0, 1, 6, 12, 17, 18, 0.939), ('Brandt', 'Snedeker', 'UNITED STATES', 133, 17, 1, 0, 1, 2, 10, 94, 0.09), ('Jeffrey', 'Kang', 'UNITED STATES', 318, 20, 0, 0, 1, 1, 7, 170, -0.958), ('Brice', 'Garnett', 'UNITED STATES', 311, 21, 0, 0, 1, 4, 8, 137, -0.525), ('Ben', 'Martin', 'UNITED STATES', 469, 11, 0, 0, 1, 2, 4, 159, -0.733), ('Aldrich', 'Potgieter', 'SOUTH AFRICA', 91, 21, 0, 0, 2, 5, 10, 71, -0.445), ('Bill', 'Haas', 'UNITED STATES', 0, 1, 0, 0, 0, 0, 1, 212, 0.245), ('Collin', 'Morikawa', 'UNITED STATES', 11, 17, 1, 0, 7, 10, 15, 14, 1.094), ('John', 'VanDerLaan', 'UNITED STATES', 293, 21, 0, 0, 1, 2, 9, 149, -0.513), ('Justin', 'Rose', 'ENGLAND', 17, 18, 1, 0, 3, 9, 13, 18, 0.402), ('Zach', 'Johnson', 'UNITED STATES', 415, 4, 0, 0, 1, 1, 3, 178, 0.855), ('Jesper', 'Svensson', 'SWEDEN', 193, 17, 0, 0, 3, 3, 7, 128, -0.386), ('Peter', 'Malnati', 'UNITED STATES', 522, 20, 0, 0, 0, 2, 10, 156, -0.694), ('J.J.', 'Spaun', 'UNITED STATES', 12, 23, 1, 0, 4, 9, 16, 30, 0.628), ('Isaiah', 'Salinda', 'UNITED STATES', 389, 8, 0, 0, 0, 0, 4, 193, -0.621), ('Chandler', 'Blanchet', 'UNITED STATES', 130, 24, 0, 1, 1, 4, 11, 113, -0.835), ('Steven', 'Fisk', 'UNITED STATES', 82, 21, 1, 0, 2, 5, 12, 70, 0.013), ('Trace', 'Crowe', 'UNITED STATES', 261, 12, 0, 0, 1, 2, 7, 147, -0.274), ('Matti', 'Schmid', 'GERMANY', 89, 22, 0, 0, 4, 5, 14, 72, -0.473), ('Thorbjørn', 'Olesen', 'DENMARK', 178, 15, 0, 0, 0, 1, 7, 169, -0.235), ('Tom', 'Hoge', 'UNITED STATES', 141, 26, 0, 0, 4, 5, 17, 84, -0.513), ('Johnny', 'Keefer', 'UNITED STATES', 66, 25, 0, 0, 4, 4, 16, 73, 0.315), ('Alex', 'Noren', 'SWEDEN', 21, 21, 0, 0, 4, 7, 16, 36, 0.489), ('Seonghyeon', 'Kim', 'SOUTH KOREA', 186, 10, 0, 0, 1, 4, 7, 131, 0.072), ('David', 'Lipsky', 'UNITED STATES', 136, 19, 0, 1, 1, 4, 11, 88, -0.258), ('Matt', 'Wallace', 'ENGLAND', 54, 18, 0, 1, 3, 4, 13, 76, 0.666), ('Hayden', 'Springer', 'UNITED STATES', 280, 13, 0, 1, 1, 3, 7, 133, -0.011), ('Michael', 'Thompson', 'UNITED STATES', 0, 1, 0, 0, 0, 0, 1, 215, -1.527), ('Stephan', 'Jaeger', 'GERMANY', 128, 22, 0, 0, 3, 6, 13, 83, 0.18), ('Sepp', 'Straka', 'AUSTRIA', 34, 20, 0, 1, 3, 5, 14, 40, -0.187), ('Tyler', 'Duncan', 'UNITED STATES', 396, 9, 0, 0, 0, 1, 4, 172, 0.211), ('Kurt', 'Kitayama', 'UNITED STATES', 40, 21, 0, 1, 4, 11, 19, 31, 0.72), ('Scottie', 'Scheffler', 'UNITED STATES', 1, 20, 3, 5, 13, 19, 19, 1, 2.249), ('Michael', 'Brennan', 'UNITED STATES', 33, 25, 1, 0, 3, 6, 19, 46, 0.439), ('Beau', 'Hossler', 'UNITED STATES', 98, 20, 0, 1, 2, 5, 12, 75, 0.762), ('Andrew', 'Putnam', 'UNITED STATES', 109, 22, 0, 1, 2, 4, 16, 80, 0.175), ('Michael', 'Kim', 'UNITED STATES', 62, 26, 0, 1, 3, 8, 19, 61, 0.271), ('Robert', 'MacIntyre', 'SCOTLAND', 19, 21, 0, 1, 6, 9, 18, 28, 0.635), ('Zachary', 'Bauchou', 'UNITED STATES', 152, 22, 0, 0, 2, 10, 17, 86, 0.517), ('Daniel', 'Berger', 'UNITED STATES', 64, 18, 0, 1, 2, 5, 12, 63, 0.153), ('Kensei', 'Hirata', 'JAPAN', 391, 21, 0, 0, 0, 2, 8, 175, -0.971), ('Davis', 'Chatfield', 'UNITED STATES', 248, 21, 0, 0, 1, 4, 10, 134, -0.027), ('Aaron', 'Wise', 'UNITED STATES', 480, 13, 0, 0, 1, 2, 3, 154, -0.379), ('Corey', 'Conners', 'CANADA', 56, 22, 0, 0, 1, 7, 20, 60, 0.132), ('Chez', 'Reavie', 'UNITED STATES', 669, 2, 0, 0, 0, 0, 1, 212, 0.245), ('Christo', 'Lamprecht', 'SOUTH AFRICA', 360, 20, 0, 0, 0, 0, 5, 198, -1.915), ('Zecheng', 'Dou', 'CHINA', 175, 22, 0, 0, 1, 7, 12, 111, 0.464), ('Dylan', 'Frittelli', 'SOUTH AFRICA', 487, 3, 0, 0, 0, 0, 1, 219, -0.409), ('Lanto', 'Griffin', 'UNITED STATES', 238, 17, 0, 0, 0, 2, 8, 161, -0.494), ('Benjamin', 'James', 'UNITED STATES', 92, 9, 0, 1, 3, 5, 8, 66, 1.381), ('Lee', 'Hodges', 'UNITED STATES', 142, 18, 0, 0, 2, 5, 11, 109, 0.261), ('Keith', 'Mitchell', 'UNITED STATES', 77, 23, 0, 0, 3, 6, 20, 51, 0.641), ('Marcelo', 'Rozo', 'COLOMBIA', 639, 21, 0, 0, 0, 0, 4, 202, -1.65), ('Chandler', 'Phillips', 'UNITED STATES', 138, 21, 0, 0, 2, 7, 13, 96, 0.038), ('Nicholas', 'Lindheim', 'UNITED STATES', 0, 3, 0, 0, 0, 0, 1, 217, -2.853), ('Ryan', 'Brehm', 'UNITED STATES', 0, 9, 0, 0, 0, 0, 2, 200, -2.202), ('Austin', 'Eckroat', 'UNITED STATES', 203, 21, 0, 0, 2, 4, 16, 117, 0.117), ('Sahith', 'Theegala', 'UNITED STATES', 86, 25, 0, 0, 4, 9, 24, 48, 0.178), ('Padraig', 'Harrington', 'IRELAND', 655, 5, 0, 0, 0, 1, 1, 187, -0.784), ('Chan', 'Kim', 'UNITED STATES', 295, 10, 0, 0, 0, 0, 7, 181, 0.059), ('J.T.', 'Poston', 'UNITED STATES', 38, 22, 1, 0, 3, 7, 16, 32, 0.269), ('Martin', 'Laird', 'SCOTLAND', 576, 5, 0, 0, 0, 0, 2, 209, -1.292), ('Zac', 'Blair', 'UNITED STATES', 144, 14, 0, 0, 3, 4, 10, 124, 0.487), ('Luke', 'Clanton', 'UNITED STATES', 340, 20, 0, 0, 1, 2, 9, 150, -0.651), ('Carson', 'Young', 'UNITED STATES', 201, 9, 0, 0, 0, 0, 6, 197, -0.093), ('Paul', 'Peterson', 'UNITED STATES', 296, 12, 0, 0, 1, 3, 6, 155, -0.017), ('Davis', 'Riley', 'UNITED STATES', 132, 23, 0, 0, 2, 3, 11, 115, -0.968), ('Tom', 'Kim', 'SOUTH KOREA', 32, 23, 1, 0, 4, 9, 20, 14, 0.827), ('Joe', 'Highsmith', 'UNITED STATES', 247, 22, 0, 0, 1, 1, 12, 152, -0.875), ('David', 'Ford', 'UNITED STATES', 373, 10, 0, 0, 0, 2, 6, 158, 0.04), ('Erik', 'Van Rooyen', 'SOUTH AFRICA', 226, 21, 0, 0, 0, 3, 9, 148, -0.335), ('Sam', 'Stevens', 'UNITED STATES', 63, 25, 0, 0, 3, 7, 19, 58, -0.125), ('Brian', 'Harman', 'UNITED STATES', 65, 22, 0, 0, 1, 6, 17, 68, 0.168), ('Harry', 'Hall', 'ENGLAND', 69, 23, 0, 0, 4, 7, 13, 56, 0.269), ('Rico', 'Hoey', 'PHILIPPINES', 110, 24, 0, 0, 0, 5, 19, 114, 0.026), ('Jordan', 'Spieth', 'UNITED STATES', 59, 22, 0, 0, 0, 10, 19, 52, 0.467), ('Seamus', 'Power', 'IRELAND', 190, 20, 0, 0, 3, 6, 13, 104, 0.278), ('Dylan', 'Wu', 'UNITED STATES', 442, 21, 0, 0, 0, 0, 10, 164, -0.634), ('Min Woo', 'Lee', 'AUSTRALIA', 31, 20, 0, 2, 5, 9, 17, 4, 0.729), ('Adrien', 'Saddier', 'FRANCE', 155, 17, 0, 0, 0, 0, 9, 180, -0.279), ('Danny', 'Walker', 'UNITED STATES', 323, 22, 0, 0, 0, 1, 10, 162, -0.971), ('A.J.', 'Ewart', 'CANADA', 198, 22, 0, 0, 0, 6, 15, 108, 0.271), ('Si Woo', 'Kim', 'SOUTH KOREA', 14, 24, 0, 3, 11, 14, 23, 14, 1.182), ('Jonathan', 'Byrd', 'UNITED STATES', 600, 7, 0, 0, 0, 0, 5, 196, -0.002), ('Matthew', 'McCarty', 'UNITED STATES', 76, 26, 0, 1, 4, 8, 18, 50, -0.168), ('Harry', 'Higgs', 'UNITED STATES', 383, 12, 0, 0, 0, 1, 4, 185, -0.382), ('Emilio', 'Gonzalez', 'MEXICO', 278, 4, 0, 0, 0, 0, 2, 204, -1.355), ('Marco', 'Penge', 'ENGLAND', 53, 17, 0, 0, 2, 5, 11, 105, -0.041), ('Pierceson', 'Coody', 'UNITED STATES', 70, 26, 0, 1, 2, 11, 17, 54, 0.079), ('Viktor', 'Hovland', 'NORWAY', 13, 19, 1, 1, 4, 9, 15, 2, 0.759), ('Nick', 'Taylor', 'CANADA', 85, 24, 0, 0, 1, 5, 22, 65, 0.304), ('Adam', 'Hadwin', 'CANADA', 325, 12, 0, 0, 0, 1, 5, 182, -0.672), ('David', 'Skinns', 'ENGLAND', 302, 13, 0, 0, 1, 4, 8, 139, -0.003), ('Xander', 'Schauffele', 'UNITED STATES', 10, 20, 0, 1, 7, 13, 18, 14, 1.008), ('Doug', 'Ghim', 'UNITED STATES', 156, 19, 0, 0, 2, 7, 14, 89, 0.999), ('Kevin', 'Streelman', 'UNITED STATES', 433, 16, 0, 0, 1, 2, 8, 151, -0.057), ('Ludvig', 'Åberg', 'SWEDEN', 18, 20, 0, 0, 9, 14, 17, 4, 1.19), ('Wyndham', 'Clark', 'UNITED STATES', 5, 23, 3, 0, 6, 13, 18, 21, 1.147), ('Rickie', 'Fowler', 'UNITED STATES', 49, 21, 0, 1, 5, 10, 16, 33, 0.496), ('Danny', 'Willett', 'ENGLAND', 372, 10, 0, 0, 0, 1, 5, 186, -0.501), ('Patrick', 'Fishburn', 'UNITED STATES', 256, 19, 0, 0, 0, 2, 11, 146, 0.086), ('Brian', 'Campbell', 'UNITED STATES', 176, 23, 0, 0, 0, 1, 9, 168, -1.535), ('Vijay', 'Singh', 'FIJI', 0, 2, 0, 0, 0, 0, 1, 203, 0.468), ('Pontus', 'Nyholm', 'SWEDEN', 284, 21, 0, 0, 0, 3, 10, 136, -0.438), ('Seung-Yul', 'Noh', 'SOUTH KOREA', 370, 4, 0, 0, 0, 1, 2, 189, -0.045), ('Alex', 'Fitzpatrick', 'ENGLAND', 57, 14, 1, 0, 6, 8, 13, 4, 0.644), ('Jordan L.', 'Smith', 'ENGLAND', 73, 22, 0, 0, 1, 8, 16, 69, 0.367), ('Ryan', 'Fox', 'NEW ZEALAND', 23, 19, 1, 0, 3, 8, 17, 26, 0.069), ('Austin', 'Smotherman', 'UNITED STATES', 121, 22, 0, 1, 2, 6, 13, 79, -0.143), ('Adrien', 'Dumont De Chassart', 'BELGIUM', 210, 21, 0, 0, 0, 4, 12, 126, 0.068), ('Jhonattan', 'Vegas', 'VENEZUELA', 206, 16, 0, 0, 0, 2, 9, 143, -1.065), ('Jeremy', 'Paul', 'GERMANY', 334, 12, 0, 0, 1, 1, 4, 184, -1.855), ('Keita', 'Nakajima', 'JAPAN', 96, 16, 0, 0, 1, 4, 8, 120, 0.485), ('Karl', 'Vilips', 'AUSTRALIA', 212, 20, 0, 0, 0, 4, 11, 127, -0.143), ('Charley', 'Hoffman', 'UNITED STATES', 689, 15, 0, 0, 0, 0, 1, 207, -1.768), ('Webb', 'Simpson', 'UNITED STATES', 475, 11, 0, 0, 0, 2, 5, 165, -0.244), ('Mark', 'Hubbard', 'UNITED STATES', 160, 22, 0, 1, 1, 2, 12, 122, -0.642), ('John', 'Parry', 'ENGLAND', 101, 22, 0, 0, 1, 7, 18, 91, 0.212), ('Gary', 'Woodland', 'UNITED STATES', 43, 22, 1, 0, 6, 8, 16, 29, 0.436), ('Christiaan', 'Bezuidenhout', 'SOUTH AFRICA', 102, 22, 0, 0, 2, 6, 18, 99, 0.722), ('Ben', 'Griffin', 'UNITED STATES', 25, 25, 0, 0, 4, 9, 19, 41, 0.495), ('Mackenzie', 'Hughes', 'CANADA', 161, 21, 0, 0, 2, 5, 14, 116, 0.375), ('Brooks', 'Koepka', 'UNITED STATES', 129, 16, 0, 0, 1, 6, 11, 98, 0.633), ('Emiliano', 'Grillo', 'ARGENTINA', 113, 21, 0, 0, 2, 4, 12, 112, -0.053), ('Taylor', 'Pendrith', 'CANADA', 104, 25, 0, 1, 2, 2, 15, 95, -0.184), ('Chris', 'Kirk', 'UNITED STATES', 106, 20, 0, 0, 2, 2, 12, 118, 0.154), ('Taylor', 'Moore', 'UNITED STATES', 185, 17, 0, 1, 1, 4, 11, 106, 0.135), ('Troy', 'Merritt', 'UNITED STATES', 419, 9, 0, 0, 0, 1, 7, 179, -0.212), ('Shane', 'Lowry', 'IRELAND', 39, 18, 0, 1, 2, 6, 13, 64, 0.595), ('Hao-Tong', 'Li', 'CHINA', 116, 23, 0, 0, 2, 3, 9, 121, -0.056), ('Matt', 'Kuchar', 'UNITED STATES', 215, 15, 0, 0, 0, 4, 7, 145, -0.103), ('Billy', 'Horschel', 'UNITED STATES', 164, 25, 0, 0, 1, 5, 15, 101, -0.078), ('Maverick', 'McNealy', 'UNITED STATES', 48, 21, 0, 0, 3, 12, 19, 42, 0.862), ('Justin', 'Lower', 'UNITED STATES', 349, 18, 0, 0, 0, 0, 10, 173, -0.642), ('Nick', 'Dunlap', 'UNITED STATES', 454, 19, 0, 0, 0, 3, 8, 167, -1.078), ('Frankie', 'Capan', 'UNITED STATES', 488, 6, 0, 0, 0, 0, 1, 211, -3.604), ('Seung-taek', 'Lee', 'SOUTH KOREA', 429, 4, 0, 0, 0, 0, 1, 205, -1.337), ('Nicolas', 'Echavarria', 'COLOMBIA', 61, 25, 1, 0, 3, 5, 16, 45, -0.379), ('Ryo', 'Hisatsune', 'JAPAN', 67, 26, 0, 1, 5, 8, 23, 47, 0.351), ('Chris', 'Gotterup', 'UNITED STATES', 7, 23, 3, 0, 7, 14, 21, 4, 1.144), ('Joel', 'Dahmen', 'UNITED STATES', 243, 21, 0, 0, 2, 3, 11, 123, -0.098), ('Brendon', 'Todd', 'UNITED STATES', 967, 7, 0, 0, 0, 0, 1, 218, -2.282), ('Will', 'Zalatoris', 'UNITED STATES', 585, 4, 0, 0, 0, 1, 2, 191, -0.244), ('Sami', 'Välimäki', 'FINLAND', 84, 13, 0, 0, 0, 1, 6, 157, -0.32), ('Adam', 'Scott', 'AUSTRALIA', 44, 19, 0, 0, 3, 12, 17, 11, 0.556), ('Matthieu', 'Pavon', 'FRANCE', 258, 21, 0, 0, 0, 4, 10, 130, -0.32), ('Ricky', 'Castillo', 'UNITED STATES', 81, 20, 1, 0, 3, 4, 19, 57, 0.222), ('William', 'McGirt', 'UNITED STATES', 993, 4, 0, 0, 0, 0, 1, 220, -1.764), ('Adam', 'Svensson', 'CANADA', 528, 20, 0, 0, 0, 0, 10, 176, -0.661), ('Takumi', 'Kanaya', 'JAPAN', 188, 22, 0, 0, 0, 2, 13, 142, -0.064), ('Ryan', 'Gerard', 'UNITED STATES', 22, 26, 0, 3, 7, 11, 22, 3, 0.805), ('Vince', 'Whaley', 'UNITED STATES', 220, 22, 0, 0, 0, 0, 8, 174, -0.693), ('Davis', 'Thompson', 'UNITED STATES', 123, 21, 0, 0, 4, 7, 14, 82, 0.467), ('Eric', 'Cole', 'UNITED STATES', 78, 25, 0, 1, 4, 6, 19, 49, 0.431), ('Russell', 'Henley', 'UNITED STATES', 6, 20, 1, 0, 6, 14, 17, 4, 0.895)]

In [14]:
df = pd.DataFrame(rows, columns=column_names)

In [15]:
df.head()

,first_name,last_name,country,world_rank,events_played,first_place,second_place,top_10,top_25,cuts_made,fed_ex_rank,strokes_gained_total
0,Rory,McIlroy,NORTHERN IRELAND,2,14,1,1,6,9,14,4,1.341
1,Jackson,Suber,UNITED STATES,94,20,0,0,3,6,13,74,0.475
2,Nicolai,Højgaard,DENMARK,42,21,0,2,4,8,16,35,0.691
3,Kris,Ventura,NORWAY,195,19,0,1,3,5,7,107,0.195
4,Gordon,Sargent,UNITED STATES,331,18,0,1,2,3,7,132,-0.694

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   first_name            219 non-null    str
 1   last_name             219 non-null    str
 2   country               219 non-null    str
 3   world_rank            219 non-null    int64
 4   events_played         219 non-null    int64
 5   first_place           219 non-null    int64
 6   second_place          219 non-null    int64
 7   top_10                219 non-null    int64
 8   top_25                219 non-null    int64
 9   cuts_made             219 non-null    int64
 10  fed_ex_rank           219 non-null    int64
 11  strokes_gained_total  219 non-null    float64
dtypes: float64(1), int64(8), str(3)
memory usage: 20.7 KB

In [17]:
df["country"] = df["country"].str.title()
df.head()

,first_name,last_name,country,world_rank,events_played,first_place,second_place,top_10,top_25,cuts_made,fed_ex_rank,strokes_gained_total
0,Rory,McIlroy,Northern Ireland,2,14,1,1,6,9,14,4,1.341
1,Jackson,Suber,United States,94,20,0,0,3,6,13,74,0.475
2,Nicolai,Højgaard,Denmark,42,21,0,2,4,8,16,35,0.691
3,Kris,Ventura,Norway,195,19,0,1,3,5,7,107,0.195
4,Gordon,Sargent,United States,331,18,0,1,2,3,7,132,-0.694

In [18]:
events = df["events_played"].where(df["events_played"] > 0)

df["win_pct"] = (df["first_place"] / events * 100).round(2)
df["top_10_pct"] = (df["top_10"] / events * 100).round(2)

df.head()

,first_name,last_name,country,world_rank,events_played,first_place,second_place,top_10,top_25,cuts_made,fed_ex_rank,strokes_gained_total,win_pct,top_10_pct
0,Rory,McIlroy,Northern Ireland,2,14,1,1,6,9,14,4,1.341,7.14,42.86
1,Jackson,Suber,United States,94,20,0,0,3,6,13,74,0.475,0.00,15.00
2,Nicolai,Højgaard,Denmark,42,21,0,2,4,8,16,35,0.691,0.00,19.05
3,Kris,Ventura,Norway,195,19,0,1,3,5,7,107,0.195,0.00,15.79
4,Gordon,Sargent,United States,331,18,0,1,2,3,7,132,-0.694,0.00,11.11

# ------------ LOAD ----------------

In [19]:
MY_SQL_HOST = os.getenv("MYSQL_HOST")
MY_SQL_PORT = os.getenv("MYSQL_PORT")
MY_SQL_USER = os.getenv("MYSQL_USER")
MY_SQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MY_SQL_DATABASE = os.getenv("MYSQL_DATABASE")

engine = create_engine(
    f"mysql+pymysql://{MY_SQL_USER}:{MY_SQL_PASSWORD}@{MY_SQL_HOST}:{MY_SQL_PORT}/{MY_SQL_DATABASE}"
)


table_name = 'players_statistics'
df.to_sql(table_name,engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table {table_name} in database {MY_SQL_DATABASE}")

Data successfully loaded into table players_statistics in database pga_db